# Generated by Django 5.2.6 on 2025-09-20 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_created_at_and_more'),
        ('users', '0002_profile_username_alter_profile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='onwer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
