# Generated by Django 5.2.6 on 2025-09-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_onwer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='onwer',
            new_name='owner',
        ),
    ]
