# Generated by Django 5.2.6 on 2025-10-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_review_owner'),
        ('users', '0005_alter_profile_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
